#################
### AUTOSTART ###
#################

# Notification daemon
exec-once = mako

# Wallpaper (tu dois avoir une image à ~/.config/hypr/wallpaper.jpg)
exec-once = hyprpaper

# Network manager applet
exec-once = nm-applet --indicator

# Polkit agent for sudo
exec-once = /usr/lib/polkit-kde-agent-1

# XDG autostart

# Wallpaper daemon
exec-once = swww-daemon &
exec-once = sleep 1 && swww img /home/jonat/.config/hypr/wallpapers/shaded_landscape_real.png

# Status bar
exec-once = waybar > /dev/null 2>&1 &

exec-once = hypridle

