general {
    no_fade_in = true
    grace = 0
    disable_loading = true
}

background {
    monitor =
    # Chemin exact vers ton image vu dans ton arborescence
    path = /home/jonat/.config/hypr/wallpapers/shaded_landscape_real.png
    blur_passes = 2
    contrast = 0.8916
    brightness = 0.8172
}

# HEURE (Centrée, style imposant)
label {
    monitor =
    text = $TIME
    color = rgba(205, 214, 244, 1.0)
    font_size = 120
    font_family = JetBrainsMono Nerd Font ExtraBold
    position = 0, 80
    halign = center
    valign = center
}

# CHAMP DE SAISIE (Look moderne)
input-field {
    monitor =
    size = 250, 60
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    outer_color = rgba(180, 190, 254, 0.5)
    inner_color = rgba(30, 30, 46, 0.7)
    font_color = rgb(205, 214, 244)
    fade_on_empty = true
    placeholder_text = <i>Password...</i>
    hide_input = false
    position = 0, -50
    halign = center
    valign = center
}
