general {
    lock_cmd = pidof hyprlock || hyprlock       # Commande pour verrouiller
    before_sleep_cmd = loginctl lock-session    # Verrouiller avant la mise en veille
    after_sleep_cmd = hyprctl dispatch dpms on  # Rallumer l'écran au réveil
}

# 1. Baisser la luminosité de l'écran (Économie d'énergie)
listener {
    timeout = 150                                # 2min 30s
    on-timeout = brightnessctl set 10%           # Baisse la luminosité à 10%
    on-resume = brightnessctl set 100%           # Remet à 100% au retour
}

# 2. Verrouiller l'écran
listener {
    timeout = 300                                # 5 minutes
    on-timeout = loginctl lock-session           # Lance hyprlock
}

# 3. Éteindre l'écran complètement (DPMS)
listener {
    timeout = 330                                # 5min 30s
    on-timeout = hyprctl dispatch dpms off       # Éteint le signal écran
    on-resume = hyprctl dispatch dpms on         # Rallume le signal au retour
}

# 4. Mise en veille du PC (Suspend)
listener {
    timeout = 1800                               # 30 minutes
    on-timeout = systemctl suspend               # Met le PC en veille
}
