#################
### HYPRPAPER ###
#################

preload = /home/jonat/.config/hypr/wallpapers/shaded_landscape_real.png
wallpaper = eDP-1,/home/jonat/.config/hypr/wallpapers/shaded_landscape_real.png

splash = false
ipc = off
